"""add auth sessions and checkout idempotency

Revision ID: 6e692f7faa29
Revises: 6cc6bb9b0ebf
Create Date: 2026-09-13 22:31:59.411093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e692f7faa29'
down_revision = '6cc6bb9b0ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_jti', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.create_index('uq_active_cart_per_user', ['user_id'], unique=True, sqlite_where=sa.text("user_id IS NOT NULL AND status = 'active'"), postgresql_where=sa.text("user_id IS NOT NULL AND status = 'active'"))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idempotency_key', sa.String(length=128), nullable=True))
        batch_op.create_unique_constraint('uq_orders_user_idempotency', ['user_id', 'idempotency_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('uq_orders_user_idempotency', type_='unique')
        batch_op.drop_column('idempotency_key')

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_index('uq_active_cart_per_user', sqlite_where=sa.text("user_id IS NOT NULL AND status = 'active'"), postgresql_where=sa.text("user_id IS NOT NULL AND status = 'active'"))

    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_jti'))

    op.drop_table('auth_sessions')
    # ### end Alembic commands ###
