"""Claudinary

Revision ID: 7a991d763aba
Revises: c4d8a1e2f7b9
Create Date: 2026-09-18 00:57:41.832792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a991d763aba'
down_revision = 'c4d8a1e2f7b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('password_reset_tokens_token_hash_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('password_reset_tokens_token_hash_key'), ['token_hash'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
