"""add order address snapshot

Revision ID: 893155259edd
Revises: 6e692f7faa29
Create Date: 2026-09-13 22:39:41.243574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '893155259edd'
down_revision = '6e692f7faa29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shipping_address_snapshot', sa.JSON(), nullable=True))
        batch_op.create_foreign_key(
            'fk_orders_address_id_addresses', 'addresses', ['address_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_address_id_addresses', type_='foreignkey')
        batch_op.drop_column('shipping_address_snapshot')
        batch_op.drop_column('address_id')

    # ### end Alembic commands ###
